version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      
      - run:
          name: Run Tests
          command: |
            pytest
            pytest --cov
            pytest --cov --cov-report=html

      - run:
          name: Build and push Docker image
          command: |
            echo "Building and pushing Docker image..."
            docker build -t ghcr.io/nicolasmunoz13/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
            echo "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" | docker login ghcr.io -u "nicolasmunoz13" --password-stdin
            docker push ghcr.io/nicolasmunoz13/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

workflows:

  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
