version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Build and push Docker image
          command: |
            echo "Building and pushing Docker image..."
            systemctl start docker
            systemctl enable docker
            docker build -t ghcr.io/nicolasmunoz13/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
            docker login ghcr.io -u nicolasmunoz13 -p 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
            docker push ghcr.io/nicolasmunoz13/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

workflows:

  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
