version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Build and push Docker image
          command: |
            echo circle project ${CIRCLE_PROJECT_USERNAME}
            echo circle project ${CIRCLE_PROJECT_REPONAME}
            echo circle project ${CIRCLE_SHA1}
            echo "Building and pushing Docker image..."
            docker build -t ghcr.io/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
            docker login ghcr.io -u ${GHCR_USERNAME} -p ${GHCR_TOKEN}
            docker push ghcr.io/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

workflows:

  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
