version: 2.1

jobs:
  release:
    docker:
      - image: ubuntu:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Unshallow
          command: git fetch --prune --unshallow

      - run:
          name: Get the version to publish
          command: echo "VERSION=$(echo $CIRCLE_TAG | sed 's/v//')" >> $BASH_ENV

      - setup_remote_docker

      - run:
          name: Docker Login in GHCR
          command: echo "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" | docker login ghcr.io -u "NicolasMunoz13" --password-stdin

      - run:
          name: Build and push Docker image
          command: make publish
          environment:
            VERSION: $VERSION

workflows:

  build-and-deploy:
    jobs:
      - release:
          filters:
            tags:
              only:
                - /^v.*/